# Generated by Django 4.2.6 on 2023-10-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
