# Generated by Django 4.2.6 on 2023-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_book_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'LENT')], default=0),
        ),
    ]
