# Generated by Django 4.2.6 on 2023-10-18 11:14

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
        migrations.CreateModel(
            name='GallerySlideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sender', models.CharField(max_length=255)),
                ('email_sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'UnRead'), (1, 'Read')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('facebook_page', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')])),
                ('age', models.IntegerField()),
                ('proffesion', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(upload_to='logo/')),
                ('welcome_text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('footer_text', models.TextField()),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edited'],
            },
        ),
        migrations.CreateModel(
            name='LendBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'NOT RETURNED'), (1, 'RETURNED')], default=0)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.readerprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
