# Generated by Django 4.2.6 on 2023-10-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_message_options_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GallerySlideshow',
        ),
    ]
