# Generated by Django 4.2.6 on 2023-10-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_news_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsAndEvents',
        ),
    ]
