# Generated by Django 4.2.6 on 2023-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='reader_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
